__name__ = "LiteGram"
__description__ = "A highly customizable plugin to **remove paid and bloated features** from Telegram."
__version__ = "1.3.0"
__id__ = "litegram"
__author__ = "@wepinek (fork by @feature_plugins)"
__icon__ = "feature_plugins/8"
__min_version__ = "12.1.1"
