name: Build LiteGram Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'бурмалда')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build Plugin
        run: uv run build.py --no-bump --no-minify

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v6
        with:
          name: LiteGram.Plugin
          path: dist/LiteGram.plugin

